version: '2.4'
services:
  mongo0:
    hostname: mongo0
    container_name: mongo0
    image: mongo
    ports:
      - 27017:27017
    restart: "always"
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    healthcheck:
      test: mongo --eval "printjson(rs.isMaster())" | grep ismaster | grep true

  mongo1:
    hostname: mongo1
    container_name: mongo1
    image: mongo
    ports:
      - 27018:27017
    restart: "always"
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongo2:
    hostname: mongo2
    container_name: mongo2
    image: mongo
    ports:
      - 27019:27017
    restart: "always"
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  cluster-setup:
    hostname: cluster-setup
    container_name: cluster-setup
    image: mongo
    restart: "no"
    depends_on:
      - mongo0
      - mongo1
      - mongo2
    volumes:
      - .:/scripts
    entrypoint: [ "bash", "/scripts/mongo-setup.sh" ]

  cluster-started:
    hostname: cluster-started
    container_name: cluster-started
    image: alpine
    restart: "no"
    depends_on:
      mongo0:
        condition: service_healthy
